#! /usr/bin/env bash

host='localhost'
select i in "Tutores registro" "Tutores login" "Cerrar semestre" "Alumnos Update" "Clear"; do
	   
   case "$i" in
      "Cerrar semestre")
	 read -p "Nro control tutor: " nrocontrol
	 json="\"nrocontrol_tutor\":\"$nrocontrol\""
	 echo "{$json}" > cjson.json
	 curl -H "Content-Type: application/json" --request POST --data @./cjson.json  "http://192.168.1.71:5800/tutor/finalizar-semestre";echo  
	 ;;
      "Tutores registro"*)
	 read -p "Nro control: " nrocontrol
	 read -p "Nombre: " nombre
	 read -p "Apellido 1: " apellido1
	 read -p "Apellido 2: " apellido2
	 read -p "Id carrera: " idcarrera
	 read -p "Password: " password

	 json="\"nrocontrol\":\"$nrocontrol\",\"nombre\":\"$nombre\",\"apellido1\":\"$apellido1\",\"apellido2\":\"$apellido2\",\"idcarrera\":$idcarrera,\"clave\":\"$password\""
	 echo "{$json}" > cjson.json
	 curl -H "Content-Type: application/json" --request POST --data @./cjson.json  "http://192.168.1.71:5800/tutores/registro";echo
         ;;

      "Tutores login")
	    read -p "Nro control: " nrocontrol
	    read -p "Password: " password
	    json="\"nrocontrol\":\"$nrocontrol\",\"clave\":\"$password\""
	    echo "{$json}" > cjson.json
	    curl -H "Content-Type: application/json" --request POST --data @./cjson.json  "http://192.168.1.71:5800/tutor/login";echo
	 ;;

      "Alumnos Update")
	    read -p "Nro control alumno: " nrocontrol_al
	    read -p "Nro control tutor: " nrocontrol_tu
	    read -p "Nombre materia: " codigo_mat
	    read -p "Calif: " calif
	    json="\"nrocontrol_alumno\":\"$nrocontrol_al\",\"nrocontrol_tutor\":\"$nrocontrol_tu\",\"nombre_materia\":\"$codigo_mat\",\"calificacion\":\"$calif\""
	    echo "{$json}" > cjson.json
	    curl -H "Content-Type: application/json" --request POST --data @./cjson.json  "http://192.168.1.71:5800/alumno/update";echo
	 ;;

      "Clear")
	 clear
	 ;;
   esac
done
