CALIFICACION_APROBATORIA=70
TABLE_FIELDS='tables_fields'
FIELD_VALUES='field_values'
CUSTOM_SELECT='custom_select'
FUNC_NAME='func_name'
PARAMS='params'
ERROR_FUN_MSG='error_msg'
PROC_VALUES='proc_values'
PROC_PARAMS='proc_params'
SECRET_JWT="Poo es marica"
TIMEOUT_JWT=6000